---
- name: Install and start Apache
  hosts: all
  become: true
  vars:
    nombre:  "Brandon"
    apellido: "Rodriguez"

  tasks:
    - name: Ensure apache2 is installed
      ansible.builtin.package:
        name: apache2
        state: present

    - name: Deploy index.html
      ansible.builtin.template:
        src: files/index.html
        dest: /var/www/html/index.html
        mode: '0644'

    - name: Ensure apache2 is running
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true

